function summary = airStateTable(state)
%AIRSTATETABLE Convert an airState result to a one-row summary table.

    if isempty(state.notes)
        noteText = "";
    else
        noteText = strjoin(state.notes, " | ");
    end

    summary = table( ...
        string(state.fluid), ...
        logical(state.isComplete), ...
        string(state.model), ...
        state.T_C, ...
        state.T_K, ...
        state.P_kPa, ...
        state.v_m3_kg, ...
        state.rho_kg_m3, ...
        state.u_kJ_kg, ...
        state.h_kJ_kg, ...
        state.s_kJ_kg_K, ...
        state.s0_kJ_kg_K, ...
        state.Pr_relative, ...
        state.vr_relative, ...
        state.cp_kJ_kg_K, ...
        state.cv_kJ_kg_K, ...
        state.k_ratio, ...
        state.k_W_m_K, ...
        state.mu_Pa_s, ...
        state.nu_m2_s, ...
        state.alpha_m2_s, ...
        state.Prandtl, ...
        string(state.source), ...
        string(noteText), ...
        'VariableNames', { ...
            'Fluid','Complete','Model','T_C','T_K','P_kPa', ...
            'v_m3_kg','rho_kg_m3','u_kJ_kg','h_kJ_kg', ...
            's_kJ_kg_K','s0_kJ_kg_K','Pr_relative','vr_relative', ...
            'cp_kJ_kg_K','cv_kJ_kg_K','k_ratio','k_W_m_K', ...
            'mu_Pa_s','nu_m2_s','alpha_m2_s','Prandtl', ...
            'Source','Notes'});
end
