function summary = r134aStateTable(state)
%R134ASTATETABLE Convert an r134aState result to a one-row summary table.

    if isempty(state.notes)
        noteText = "";
    else
        noteText = strjoin(state.notes, " | ");
    end
    candidateCount = height(state.candidates);

    summary = table( ...
        string(state.fluid), ...
        logical(state.isComplete), ...
        string(state.phase), ...
        state.T_C, ...
        state.P_kPa, ...
        state.v_m3_kg, ...
        state.u_kJ_kg, ...
        state.h_kJ_kg, ...
        state.s_kJ_kg_K, ...
        state.x, ...
        candidateCount, ...
        string(state.source), ...
        string(noteText), ...
        'VariableNames', { ...
            'Fluid','Complete','Phase','T_C','P_kPa','v_m3_kg', ...
            'u_kJ_kg','h_kJ_kg','s_kJ_kg_K','x', ...
            'CandidateCount','Source','Notes'});
end
